import Amplify, { Auth } from "aws-amplify";

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const React = require("react");
const awsmobile = {
  aws_project_region: "eu-west-2",
  aws_cognito_region: "eu-west-2",
  aws_user_pools_id: "eu-west-2_DDpK7hUv1",
  aws_user_pools_web_client_id: "u3qcqugp1o8fkbvps030lrt78",
  oauth: {
    domain: "s-mart.auth.eu-west-2.amazoncognito.com",
  },
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    "NAME",
    "FAMILY_NAME",
    "PICTURE",
    "EMAIL",
    "GENDER",
    "BIRTHDATE",
    "PHONE_NUMBER",
    "ADDRESS",
  ],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_UPPERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
