import Amplify, { Auth } from "aws-amplify";

/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-west-2",
  aws_cognito_identity_pool_id:
    "eu-west-2:6f775e73-afa3-4653-ba2c-d6b5a6a32b1d",
  aws_cognito_region: "eu-west-2",
  aws_user_pools_id: "eu-west-2_FSJX1wS0w",
  aws_user_pools_web_client_id: "8v0eqte1ui2orori3r943ka8p",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;

const React = require("react");
Amplify.configure(awsConfig);
